---
- name: Install X11
  become: true
  dnf: name={{ item }} state=present
  with_items:
    - '@base-x'
    - '@fonts'
    - i3
    - i3status
    - i3lock
    - feh
    - rxvt-unicode-256color

- name: Install X11 applications
  become: true
  dnf: name={{ item }} state=present
  with_items:
    - firefox