---
- name: Install additions
  become: true
  dnf: name={{ item }} state=present
  with_items:
      - gnupg2-smime
      - pinentry-gtk
      - ykpers

- name: Create .gnupg directory
  file: path=~{{ ansible_user_id }}/.gnupg state=directory mode=0700

- name: Copy gpg-agent.conf
  copy: src=gpg-agent.conf dest=~{{ ansible_user_id }}/.gnupg/gpg-agent.conf mode=0600
