---
- name: Install base utilities
  become: true
  dnf: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - polkit
    - acpid
    - net-tools
    - bind-utils
    - nfs-utils
    - zsh
    - vim

- name: Enable services
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - acpid
    - polkit

- name: Disable SSH password authentication
  become: true
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh
