---
- name: Install base utilities
  become: true
  dnf: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - polkit
    - net-tools
    - bind-utils
    - nfs-utils
    - zsh
    - vim
    - openconnect
    - screen
    - aria2
    - binutils
    - gcc
    - autossh

- name: Enable polkit
  become: true
  service: name=polkit state=started enabled=yes

- name: Disable SSH password authentication
  become: true
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh
