---
- name: Install base utilities
  become: true
  dnf: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - polkit
    - net-tools
    - bind-utils
    - nfs-utils
    - zsh
    - vim
    - openconnect
    - gnupg2-smime

- name: Enable polkit
  become: true
  service: name=polkit state=started enabled=yes

- name: Disable SSH password authentication
  become: true
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- name: Create .gnupg directory
  file: path=~{{ ansible_user_id }}/.gnupg state=directory mode=0700

- name: Copy gpg-agent.conf
  copy: src=gpg-agent.conf dest=~{{ ansible_user_id }}/.gnupg/gpg-agent.conf mode=0600

- name: Add udev rule for Yubikey
  become: true
  copy: 
    dest: /etc/udev/rules.d/60-yubikey.rule
    content: 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0111", OWNER="{{ ansible_user_id }}"'
