---
- name: Install PHP 7.2
  apt: name={{item}} state=present
  with_items:
    - php7.2-cli
    - php7.2-curl
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xml
    - php7.2-zip
    - php7.2-gd
    - php-imagick
    - php-redis
    - php-apcu
